skillMetadata:
   sections:
      - name: Settings
        fields:
          - name: "url"
            type: "text"
            label: "Engine URL"
            value: ""
            placeholder: "Engine URL"
          - name: "api_key"
            type: "text"
            label: "API_KEY"
            value: ""
            placeholder: "API_KEY"
          - name: "device"
            type: "text"
            label: "Mycroft Device Name"
            value: "Le Restaurant"
            placeholder: "Mycroft Device Name"
            placeholder: API_KEY