skillMetadata:
   sections:
      - name: Settings
        fields:
          - name: "URL"
            type: "text"
            label: "Engine URL"
            value: ""
            placeholder: "Engine URL"
          - name: "Auth Key"
            type: "text"
            label: "API_KEY"
            value: ""
            placeholder: "API_KEY"
          - name: "Device"
            type: "text"
            label: "Mycroft Device Name"
            value: "Le Restaurant"
            placeholder: "Mycroft Device Name"
